---
- name: Deploy nginx gateway for (domain)
  hosts: nginx-gateway
  roles:
    - machine-setup
    - users-groups
    - certbot
    - nginx
    - nginx-sites
    - static-files
    - node-exporter
    - fail2ban

...
