---
- name: Install and configure fail2ban for nginx
  block:

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

    - name: Ensure fail2ban is enabled and started
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: true

    - name: Create fail2ban jail configuration for nginx
      ansible.builtin.template:
        src: ../templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

    - name: Create nginx fail2ban filter
      ansible.builtin.template:
        src: ../templates/nginx-badbots.conf.j2
        dest: /etc/fail2ban/filter.d/nginx-badbots.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

...
