---
- name: Prepare certbot config
  become: true
  block:
    - name: Create letsencrypt directory
      ansible.builtin.file:
        name: /var/www/letsencrypt
        state: directory

    - name: Create certbot directory
      ansible.builtin.file:
        name: /root/certbot/
        state: directory

- name: Install and configure certbot
  become: true
  block:
    - name: Install Certbot
      ansible.builtin.apt:
        name: certbot
        state: present
      when: ansible_os_family == 'Debian'

- name: Check and generate DH params for letsencrypt
  become: true
  block:
    - name: Check if ssl-dhparams.pem already exists
      ansible.builtin.stat:
        path: /etc/letsencrypt/ssl-dhparams.pem
      register: dhparams_file

    - name: Generate DH params if not already present
      ansible.builtin.command:
        cmd: "openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048"
      when: not dhparams_file.stat.exists

    - name: Set correct permissions for ssl-dhparams.pem
      ansible.builtin.file:
        path: /etc/letsencrypt/ssl-dhparams.pem
        owner: root
        group: letsencrypt
        mode: "0644"

- name: Prepare systemd configs for service and renewal
  become: true
  block:
    - name: Configure certbot service
      ansible.builtin.template:
        src: ../templates/certbot.service.j2
        dest: /etc/systemd/system/certbot.service
        owner: root
        group: root
        mode: "0644"

    - name: Configure systemd timer
      ansible.builtin.template:
        src: ../templates/certbot.timer.j2
        dest: /etc/systemd/system/certbot.timer
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Ensure certbot.timer is started and enabled on boot
      ansible.builtin.systemd:
        name: certbot.timer
        state: started
        enabled: true

...
